{% set name = "stripe" %}
{% set version = "14.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f2d56345bf5d41c1f21f814b00174a3173a0b5eb4e8fc46a8f779e3d7a2efc6e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - flit-core >=3.11,<4
  run:
    - python
    - requests >=2.20  # [py>=30]
    - typing-extensions >3.7.2,<=4.2.0  # [py<37]
    - typing-extensions >=4.5.0  # [py>=37]
    - typing_extensions >=4.5.0  # [py>=37]

test:
  requires:
    - pip
    - typing-extensions
  imports:
    - stripe
    - stripe.api_resources
    - stripe.api_resources.abstract
    - stripe.api_resources.issuing
    - stripe.api_resources.sigma
  commands:
    - pip check

about:
  home: https://github.com/stripe/stripe-python
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Stripe python bindings
  description: |
    Stripe is the best software platform for running an internet business.
  doc_url: https://stripe.com/docs/api/python#intro
  doc_source_url: https://github.com/stripe/stripe-python
  dev_url: https://github.com/stripe/stripe-python

extra:
  recipe-maintainers:
    - nehaljwani
